"""PDF and Excel generation for Store requisitions.

The PDF is built multi-page from the start: a 25-ingredient biryani or a thali
overflows one A4 page, and a fixed-canvas layout would either clip rows or
break outright.
"""

import io
from datetime import datetime

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from scaling import format_qty

MESS_TITLE = "OFFICERS' MESS"
DOC_TITLE = "INGREDIENT REQUIREMENT — STORE REQUISITION"

_TABLE_HEADINGS = [
    "S.No",
    "Ingredient",
    "Base Qty",
    "Exact Qty",
    "Required Qty",
    "Unit",
]

# Excel keeps quantities as real numbers so Store staff can sort and sum them,
# which means the exact figure needs its own unit column rather than the unit
# printed inline as it is on the PDF.
_EXCEL_HEADINGS = [
    "S.No",
    "Ingredient",
    "Base Qty",
    "Exact Qty",
    "Exact Unit",
    "Required Qty",
    "Unit",
]


def _draw_page_furniture(canvas, doc):
    """Header band and page number, repeated on every page via onPage."""
    canvas.saveState()
    width, height = A4

    canvas.setFont("Helvetica-Bold", 14)
    canvas.drawCentredString(width / 2.0, height - 18 * mm, MESS_TITLE)
    canvas.setFont("Helvetica-Bold", 10)
    canvas.drawCentredString(width / 2.0, height - 24 * mm, DOC_TITLE)

    canvas.setLineWidth(0.8)
    canvas.line(18 * mm, height - 27 * mm, width - 18 * mm, height - 27 * mm)

    canvas.setFont("Helvetica", 8)
    canvas.drawCentredString(width / 2.0, 12 * mm, f"Page {canvas.getPageNumber()}")
    canvas.drawString(18 * mm, 12 * mm, "Computer generated — Recipe Scaling System")
    canvas.restoreState()


def build_pdf(requisition, items):
    """Return the requisition as PDF bytes."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=32 * mm,  # clears the header drawn in _draw_page_furniture
        bottomMargin=18 * mm,
        title=f"Requisition {requisition['id']} — {requisition['dish_name_snapshot']}",
    )

    styles = getSampleStyleSheet()
    label = ParagraphStyle("label", parent=styles["Normal"], fontSize=9, leading=13)

    story = [Spacer(1, 3 * mm)]

    meta = [
        ["Requisition No.", str(requisition["id"]), "Dish", requisition["dish_name_snapshot"]],
        ["Course", requisition["course_name"] or "—", "Meal", requisition["meal_type"]],
        [
            "Date of Meal",
            requisition["meal_date"],
            "Base Recipe",
            f"{requisition['base_persons_snapshot']} persons",
        ],
        [
            "Prepared For",
            f"{requisition['persons_required']} persons",
            "Generated By",
            requisition["generated_by_name"] or "—",
        ],
        ["Generated On", requisition["generated_at"], "", ""],
    ]
    meta_table = Table(meta, colWidths=[28 * mm, 52 * mm, 28 * mm, 66 * mm])
    meta_table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOX", (0, 0), (-1, -1), 0.6, colors.black),
                ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.grey),
            ]
        )
    )
    story.append(meta_table)
    story.append(Spacer(1, 5 * mm))

    data = [_TABLE_HEADINGS]
    for idx, item in enumerate(items, start=1):
        data.append(
            [
                str(idx),
                item["ingredient_name"],
                f"{format_qty(item['base_quantity'])} {item['base_unit']}",
                # Exact qty carries its own unit: normalisation can leave it in
                # a different unit from the Required column (4500 g vs 4.5 kg),
                # and a bare "4500" next to a "kg" column reads as 4500 kg.
                f"{format_qty(item['exact_quantity'])} {item['base_unit']}",
                format_qty(item["display_quantity"]),
                item["display_unit"],
            ]
        )

    # repeatRows=1 reprints the column headings at the top of every page, so a
    # long ingredient list stays readable after the first page break.
    table = Table(
        data,
        colWidths=[14 * mm, 62 * mm, 30 * mm, 28 * mm, 28 * mm, 22 * mm],
        repeatRows=1,
    )
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f3a5f")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                ("FONTNAME", (4, 1), (4, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("ALIGN", (0, 0), (0, -1), "CENTER"),
                ("ALIGN", (2, 0), (-1, -1), "RIGHT"),
                ("ALIGN", (5, 0), (5, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
                ("BOX", (0, 0), (-1, -1), 0.8, colors.black),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f2f5f9")]),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    story.append(table)
    story.append(Spacer(1, 10 * mm))

    note = Paragraph(
        "<b>Note:</b> 'Exact Qty' is the true proportional figure. "
        "'Required Qty' is rounded up to a practical issuing quantity.",
        label,
    )

    signatures = Table(
        [["", "", ""], ["Prepared By", "Mess Secretary", "Store Officer"]],
        colWidths=[58 * mm, 58 * mm, 58 * mm],
        rowHeights=[16 * mm, 6 * mm],
    )
    signatures.setStyle(
        TableStyle(
            [
                ("LINEABOVE", (0, 1), (-1, 1), 0.6, colors.black),
                ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 1), (-1, 1), 9),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ]
        )
    )

    # KeepTogether stops the signature block being orphaned onto a page of its
    # own - a requisition whose signature lines landed alone on page 3 gets sent
    # straight back by the Store.
    story.append(KeepTogether([note, Spacer(1, 8 * mm), signatures]))

    doc.build(story, onFirstPage=_draw_page_furniture, onLaterPages=_draw_page_furniture)
    buffer.seek(0)
    return buffer


def build_excel(requisition, items):
    """Return the requisition as an .xlsx workbook in a BytesIO."""
    wb = Workbook()
    ws = wb.active
    ws.title = "Requirement"

    bold = Font(bold=True)
    title_font = Font(bold=True, size=14)
    header_font = Font(bold=True, color="FFFFFF")
    header_fill = PatternFill("solid", fgColor="1F3A5F")
    thin = Side(style="thin", color="999999")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)
    centre = Alignment(horizontal="center", vertical="center")

    ws.merge_cells("A1:G1")
    ws["A1"] = MESS_TITLE
    ws["A1"].font = title_font
    ws["A1"].alignment = centre

    ws.merge_cells("A2:G2")
    ws["A2"] = DOC_TITLE
    ws["A2"].font = bold
    ws["A2"].alignment = centre

    meta = [
        ("Requisition No.", requisition["id"], "Dish", requisition["dish_name_snapshot"]),
        ("Course", requisition["course_name"] or "—", "Meal", requisition["meal_type"]),
        (
            "Date of Meal",
            requisition["meal_date"],
            "Base Recipe",
            f"{requisition['base_persons_snapshot']} persons",
        ),
        (
            "Prepared For",
            f"{requisition['persons_required']} persons",
            "Generated By",
            requisition["generated_by_name"] or "—",
        ),
        ("Generated On", requisition["generated_at"], "", ""),
    ]
    row = 4
    for key1, val1, key2, val2 in meta:
        ws.cell(row=row, column=1, value=key1).font = bold
        ws.cell(row=row, column=2, value=val1)
        ws.cell(row=row, column=4, value=key2).font = bold
        ws.cell(row=row, column=5, value=val2)
        row += 1

    row += 1
    header_row = row
    for col, heading in enumerate(_EXCEL_HEADINGS, start=1):
        cell = ws.cell(row=header_row, column=col, value=heading)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = centre
        cell.border = border

    for idx, item in enumerate(items, start=1):
        row += 1
        values = [
            idx,
            item["ingredient_name"],
            f"{format_qty(item['base_quantity'])} {item['base_unit']}",
            float(item["exact_quantity"]),
            item["base_unit"],
            float(item["display_quantity"]),
            item["display_unit"],
        ]
        for col, value in enumerate(values, start=1):
            cell = ws.cell(row=row, column=col, value=value)
            cell.border = border
            if col == 6:  # Required Qty - the figure the Store acts on
                cell.font = bold
        ws.cell(row=row, column=1).alignment = centre
        ws.cell(row=row, column=5).alignment = centre
        ws.cell(row=row, column=7).alignment = centre

    row += 3
    ws.cell(row=row, column=1, value="Prepared By").font = bold
    ws.cell(row=row, column=3, value="Mess Secretary").font = bold
    ws.cell(row=row, column=6, value="Store Officer").font = bold

    for col, width in enumerate([8, 34, 16, 14, 12, 15, 12], start=1):
        ws.column_dimensions[get_column_letter(col)].width = width

    ws.freeze_panes = ws.cell(row=header_row + 1, column=1)

    buffer = io.BytesIO()
    wb.save(buffer)
    buffer.seek(0)
    return buffer


def export_filename(requisition, extension):
    dish = "".join(c if c.isalnum() else "_" for c in requisition["dish_name_snapshot"])
    stamp = datetime.now().strftime("%Y%m%d")
    return f"Requisition_{requisition['id']}_{dish}_{stamp}.{extension}"
